# Generated by Django 5.0.14 on 2026-03-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('INSTRUCTOR', 'Instructor'), ('TA', 'Teaching Assistant'), ('STUDENT', 'Student')], default='STUDENT', max_length=10),
        ),
    ]
