# Generated by Django 5.0.14 on 2026-03-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['global_number']},
        ),
        migrations.AddField(
            model_name='question',
            name='global_number',
            field=models.IntegerField(default=0),
        ),
    ]
