# Generated by Django 5.0.14 on 2026-03-16 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('difficulty_filter', models.JSONField(blank=True, default=list)),
                ('skill_filter', models.JSONField(blank=True, default=list)),
                ('num_questions', models.IntegerField()),
                ('mode', models.CharField(choices=[('PRACTICE', 'Practice'), ('ASSIGNMENT', 'Assignment')], max_length=10)),
                ('is_randomized', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('time_limit_minutes', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapters', models.ManyToManyField(blank=True, to='questions.chapter')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_assignments', to=settings.AUTH_USER_MODEL)),
                ('manually_selected_questions', models.ManyToManyField(blank=True, related_name='manual_assignments', to='questions.question')),
                ('sections', models.ManyToManyField(blank=True, to='questions.section')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_shuffle_map', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('max_score', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_questions', models.ManyToManyField(related_name='student_assignments_assigned', through='assignments.AssignedQuestion', to='questions.question')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='assignments.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'assignment')},
            },
        ),
        migrations.AddField(
            model_name='assignedquestion',
            name='student_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.studentassignment'),
        ),
        migrations.CreateModel(
            name='MistakeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('last_practiced_at', models.DateTimeField(blank=True, null=True)),
                ('times_practiced', models.IntegerField(default=0)),
                ('is_mastered', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistake_entries', to='questions.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('student', 'question')},
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeric_answer', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('text_answer', models.TextField(blank=True, default='', max_length=5000)),
                ('is_correct', models.BooleanField(null=True)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('server_elapsed_seconds', models.IntegerField(default=0)),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('instructor_feedback', models.TextField(blank=True, default='')),
                ('question_text_snapshot', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.mcchoice')),
                ('student_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assignments.studentassignment')),
            ],
            options={
                'unique_together': {('student_assignment', 'question')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='assignedquestion',
            unique_together={('student_assignment', 'question')},
        ),
    ]
