# Generated by Django 5.0.14 on 2026-03-17 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='type_filter',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
