# Generated by Django 5.0.14 on 2026-03-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignment_type_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignment',
            name='total_time_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
