# Generated by Django 5.0.14 on 2026-04-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_message_message_type_message_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignment',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
    ]
